export const paths = {
  home: '/',
  login: '/login',
  signup: '/signup',
  resetPassword: '/reset-password',
  pendingApproval: '/pending-approval',
  dashboard: '/dashboard',
  account: '/account',
  chat: '/chat',
  pwaProfile: '/profile',
  providers: '/providers',
  trainings: '/trainings',
  clients: '/clients',
  sessions: '/sessions',
  sessionDetail: (id: number | string) => `/sessions/${id}`,
  instructors: '/instructors',
  myInstructorProfile: '/instructors/me',
  calendar: '/calendar',
  reportDetail: (sessionId: number | string) => `/reports/${sessionId}`,
  pendingApprovals: '/admin/pending-approvals',
  auditLog: '/admin/audit-log',
  survey: (sessionId: number | string) => `/survey/${sessionId}`,
  superAdminLogin: '/superadmin/login',
  superAdminUsers: '/superadmin/users',
  superAdminSessions: '/superadmin/sessions',
  feedback: '/feedback',
  developerLogin: '/developer/login',
  developer: '/developer',
  developerAnnouncements: '/developer/announcements',
} as const;
