name: On main merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  docker:
    needs: verify
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-and-scan.yml
    with:
      push: true
